---
title: "SummaryStats"
output: html_document
date: "2024-03-14"
editor_options: 
  chunk_output_type: console
---

```{r setup}

min.yr <-2018
max.yr <- 2023 #needs changes with each analysis
ID<- "dethier" #change this to your user ID. You will be prompted for a password. 

source("00-setup.R")

collection<-unique(anal.param$collection)

```

Load raw collection data and summarize

```{r Load Data}

for(m in 1:length(collection)) {
  #m<-1 #for testing each species
  
data <-NULL 
data <-try(read.csv(paste(dat.dir, collection[m], ".RawData.csv", sep = "")), silent = T)

#check min and max year
max(data$survey_year)
min(data$survey_year)

data<-data %>% filter(RouteIdentifier!="`") %>% drop_na(RouteIdentifier)

#summarize the number of route run in each year
route.yr.tot<-data %>% group_by(survey_year) %>% summarise(nroute=n_distinct(RouteIdentifier))

#summarize the number of routes run in each year by Protocol
route.yr<-data %>% group_by(survey_year, protocol_id) %>% summarise(nroute=n_distinct(RouteIdentifier))

route.yr<-cast(route.yr, survey_year~ protocol_id, value=c("nroute"))
colnames(route.yr)<-c("survey_year", "NRoutes")

write.table(route.yr, file = paste(out.dir, collection[m], "RoutesPerYear.csv", sep = ""), row.names = FALSE, append = TRUE, quote = FALSE, sep = ",", col.names = TRUE)
  
#summarize the total count of each species per year
data$ObservationCount<-as.numeric(data$ObservationCount) 
species.yr<-data %>% group_by(survey_year, CommonName, protocol_id) %>% summarise(count=sum(ObservationCount))
species.yr<-cast(species.yr, CommonName+protocol_id~survey_year, value="count") 
species.yr<-species.yr %>% filter(!(is.na(CommonName)))

write.table(species.yr, file = paste(out.dir, collection[m], "SpeciesPerYear.csv", sep = ""), row.names = FALSE, append = TRUE, quote = FALSE, sep = ",", col.names = TRUE)

#Number of years a survey routes was run. 
long_route<-data %>% group_by(protocol_id, RouteIdentifier) %>% summarise(min_year = min(survey_year), max_year=max(survey_year), n_year=n_distinct(survey_year)) 

write.table(long_route, file = paste(out.dir, collection[m], "CountRouteYear.csv", sep = ""), row.names = FALSE, append = TRUE, quote = FALSE, sep = ",", col.names = TRUE)

#Number of years a volunteer participate
vol_year<-data %>% group_by(CollectorNumber, Collector)%>% summarise(min_year = min(survey_year), max_year=max(survey_year), n_year=n_distinct(survey_year)) 

write.table(vol_year, file = paste(out.dir, collection[m], "VolYear.csv", sep = ""), row.names = FALSE, append = TRUE, quote = FALSE, sep = ",", col.names = TRUE)

} #end collection loop

```

Load clean collection data and summarize